from __future__ import annotations

import math
from datetime import datetime, timezone
from dataclasses import dataclass
from html import escape
from pathlib import Path

from PySide6.QtCore import QRectF, QSize, Qt
from PySide6.QtGui import QColor, QFont, QImage, QPainter, QPainterPath, QPen
from PySide6.QtSvg import QSvgGenerator
from PySide6.QtWidgets import QGraphicsPathItem, QGraphicsRectItem, QGraphicsScene, QGraphicsTextItem

from .models import ColumnModel, DatabaseModel, TableModel


BOX_WIDTH = 330
HEADER_HEIGHT = 34
ROW_HEIGHT = 22
BOX_GAP_X = 90
BOX_GAP_Y = 80


@dataclass(frozen=True)
class BoxGeometry:
    table: TableModel
    rect: QRectF


class ErdSceneBuilder:
    def build(self, model: DatabaseModel, mode: str) -> QGraphicsScene:
        scene = QGraphicsScene()
        scene.setBackgroundBrush(QColor("#f8fafc"))
        boxes = self._layout(model.tables)

        for relationship in model.relationships:
            source = boxes.get(relationship.from_table)
            target = boxes.get(relationship.to_table)
            if source and target:
                self._add_relationship(scene, source.rect, target.rect, relationship.name)

        for geometry in boxes.values():
            self._add_table(scene, geometry, mode)

        scene.setSceneRect(scene.itemsBoundingRect().adjusted(-40, -40, 40, 40))
        return scene

    def export_png(self, scene: QGraphicsScene, output_path: Path) -> None:
        rect = self._export_rect(scene)
        image = QImage(math.ceil(rect.width()), math.ceil(rect.height()), QImage.Format_ARGB32)
        image.fill(QColor("#ffffff"))
        painter = QPainter(image)
        painter.setRenderHint(QPainter.Antialiasing)
        scene.render(painter, QRectF(image.rect()), rect)
        painter.end()
        image.save(str(output_path))

    def export_svg(self, scene: QGraphicsScene, output_path: Path) -> None:
        rect = self._export_rect(scene)
        width = max(1, math.ceil(rect.width()))
        height = max(1, math.ceil(rect.height()))

        generator = QSvgGenerator()
        generator.setFileName(str(output_path))
        generator.setSize(QSize(width, height))
        generator.setViewBox(QRectF(0, 0, width, height))
        generator.setTitle("DB ERD")
        generator.setDescription("Generated by DB ERD Desktop")

        painter = QPainter(generator)
        painter.setRenderHint(QPainter.Antialiasing)
        scene.render(painter, QRectF(0, 0, width, height), rect)
        painter.end()

    def export_drawio(self, model: DatabaseModel, output_path: Path) -> None:
        modified = datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")
        diagrams = "\n".join(
            [
                self._drawio_diagram(model, "logical", "Logical ERD"),
                self._drawio_diagram(model, "physical", "Physical ERD"),
            ]
        )
        content = (
            '<?xml version="1.0" encoding="UTF-8"?>\n'
            f'<mxfile host="DBErdDesktop" modified="{modified}" agent="DB ERD Desktop" type="device">\n'
            f"{diagrams}\n"
            "</mxfile>\n"
        )
        output_path.write_text(content, encoding="utf-8")

    def _export_rect(self, scene: QGraphicsScene) -> QRectF:
        rect = scene.itemsBoundingRect().adjusted(-50, -50, 50, 50)
        if rect.isEmpty():
            return QRectF(0, 0, 1, 1)
        return rect

    def _layout(self, tables: list[TableModel]) -> dict[str, BoxGeometry]:
        if not tables:
            return {}
        columns = max(1, math.ceil(math.sqrt(len(tables))))
        row_heights: list[float] = []
        heights = [HEADER_HEIGHT + ROW_HEIGHT * max(1, len(table.columns)) + 16 for table in tables]

        for row_index in range(math.ceil(len(tables) / columns)):
            start = row_index * columns
            end = min(start + columns, len(tables))
            row_heights.append(max(heights[start:end]))

        geometries: dict[str, BoxGeometry] = {}
        y = 0.0
        for row_index, row_height in enumerate(row_heights):
            x = 0.0
            for col_index in range(columns):
                table_index = row_index * columns + col_index
                if table_index >= len(tables):
                    break
                table = tables[table_index]
                height = heights[table_index]
                rect = QRectF(x, y, BOX_WIDTH, height)
                geometries[table.qualified_name] = BoxGeometry(table, rect)
                x += BOX_WIDTH + BOX_GAP_X
            y += row_height + BOX_GAP_Y
        return geometries

    def _add_table(self, scene: QGraphicsScene, geometry: BoxGeometry, mode: str) -> None:
        rect = geometry.rect
        table = geometry.table

        shadow = QGraphicsRectItem(rect.adjusted(3, 4, 3, 4))
        shadow.setBrush(QColor(15, 23, 42, 24))
        shadow.setPen(Qt.NoPen)
        scene.addItem(shadow)

        body = QGraphicsRectItem(rect)
        body.setBrush(QColor("#ffffff"))
        body.setPen(QPen(QColor("#cbd5e1"), 1.2))
        scene.addItem(body)

        header = QGraphicsRectItem(QRectF(rect.x(), rect.y(), rect.width(), HEADER_HEIGHT))
        header.setBrush(QColor("#1f2937") if mode == "physical" else QColor("#155e75"))
        header.setPen(Qt.NoPen)
        scene.addItem(header)

        title = self._table_title(table, mode)
        subtitle = self._table_subtitle(table, mode)
        title_item = self._text(title, 10, True, QColor("#ffffff"))
        title_item.setPos(rect.x() + 12, rect.y() + 7)
        title_item.setTextWidth(rect.width() - 24)
        scene.addItem(title_item)

        if subtitle and subtitle != title:
            subtitle_item = self._text(subtitle, 7, False, QColor("#64748b"))
            subtitle_item.setPos(rect.x() + 12, rect.y() + HEADER_HEIGHT + 5)
            subtitle_item.setTextWidth(rect.width() - 24)
            scene.addItem(subtitle_item)
            y = rect.y() + HEADER_HEIGHT + 25
        else:
            y = rect.y() + HEADER_HEIGHT + 8

        for column in table.columns:
            text_value = self._column_text(column, mode)
            item = self._text(text_value, 8, column.is_primary_key, QColor("#0f172a"))
            item.setPos(rect.x() + 12, y)
            item.setTextWidth(rect.width() - 24)
            scene.addItem(item)
            y += ROW_HEIGHT

    def _add_relationship(self, scene: QGraphicsScene, source: QRectF, target: QRectF, name: str) -> None:
        start = source.center()
        end = target.center()
        if source.right() <= target.left():
            start.setX(source.right())
            end.setX(target.left())
        elif target.right() <= source.left():
            start.setX(source.left())
            end.setX(target.right())
        elif source.bottom() <= target.top():
            start.setY(source.bottom())
            end.setY(target.top())
        else:
            start.setY(source.top())
            end.setY(target.bottom())

        middle_x = (start.x() + end.x()) / 2
        path = QPainterPath(start)
        path.lineTo(middle_x, start.y())
        path.lineTo(middle_x, end.y())
        path.lineTo(end)

        item = QGraphicsPathItem(path)
        item.setPen(QPen(QColor("#64748b"), 1.6, Qt.SolidLine, Qt.RoundCap, Qt.RoundJoin))
        item.setZValue(-10)
        scene.addItem(item)

        label = self._text(name, 7, False, QColor("#475569"))
        label.setDefaultTextColor(QColor("#475569"))
        label.setPos(middle_x + 4, (start.y() + end.y()) / 2 - 10)
        label.setTextWidth(150)
        label.setZValue(-9)
        scene.addItem(label)

    def _text(self, value: str, point_size: int, bold: bool, color: QColor) -> QGraphicsTextItem:
        item = QGraphicsTextItem(value)
        font = QFont("Segoe UI", point_size)
        font.setBold(bold)
        item.setFont(font)
        item.setDefaultTextColor(color)
        return item

    def _drawio_diagram(self, model: DatabaseModel, mode: str, name: str) -> str:
        boxes = self._layout(model.tables)
        table_ids: dict[str, str] = {}
        cells = ['      <mxCell id="0"/>', '      <mxCell id="1" parent="0"/>']

        for index, geometry in enumerate(boxes.values()):
            table_id = f"{mode}-table-{index}"
            table_ids[geometry.table.qualified_name] = table_id
            cells.extend(self._drawio_table_cells(table_id, geometry, mode))

        for index, relationship in enumerate(model.relationships):
            source = table_ids.get(relationship.from_table)
            target = table_ids.get(relationship.to_table)
            if source is None or target is None:
                continue
            cells.append(
                "      "
                f'<mxCell id="{mode}-rel-{index}" value="{self._xml(relationship.name)}" '
                'style="edgeStyle=orthogonalEdgeStyle;rounded=0;orthogonalLoop=1;jettySize=auto;html=1;'
                'strokeColor=#64748b;fontColor=#475569;startArrow=none;endArrow=none;" '
                f'edge="1" parent="1" source="{source}" target="{target}">'
                '<mxGeometry relative="1" as="geometry"/></mxCell>'
            )

        bounds = self._drawio_bounds(boxes)
        root = "\n".join(cells)
        return (
            f'  <diagram id="{mode}-erd" name="{self._xml(name)}">\n'
            f'    <mxGraphModel dx="{math.ceil(bounds.width())}" dy="{math.ceil(bounds.height())}" grid="1" gridSize="10" '
            'guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" '
            f'pageWidth="{math.ceil(bounds.width() + 120)}" pageHeight="{math.ceil(bounds.height() + 120)}" '
            'math="0" shadow="0">\n'
            "    <root>\n"
            f"{root}\n"
            "    </root>\n"
            "    </mxGraphModel>\n"
            "  </diagram>"
        )

    def _drawio_table_cells(self, table_id: str, geometry: BoxGeometry, mode: str) -> list[str]:
        rect = geometry.rect
        x = rect.x() + 40
        y = rect.y() + 40
        table = geometry.table
        cells = [
            "      "
            f'<mxCell id="{table_id}" value="" '
            'style="rounded=0;whiteSpace=wrap;html=1;fillColor=#ffffff;strokeColor=#cbd5e1;'
            'shadow=1;container=1;recursiveResize=0;collapsible=0;" vertex="1" parent="1">'
            f'<mxGeometry x="{self._num(x)}" y="{self._num(y)}" width="{self._num(rect.width())}" '
            f'height="{self._num(rect.height())}" as="geometry"/></mxCell>',
            "      "
            f'<mxCell id="{table_id}-header" value="{self._xml(self._table_title(table, mode))}" '
            f'style="rounded=0;whiteSpace=wrap;html=1;fillColor={self._drawio_header_color(mode)};'
            'strokeColor=none;fontColor=#ffffff;fontStyle=1;align=left;verticalAlign=middle;spacingLeft=12;" '
            f'vertex="1" parent="{table_id}" connectable="0">'
            f'<mxGeometry x="0" y="0" width="{self._num(rect.width())}" height="{HEADER_HEIGHT}" as="geometry"/></mxCell>',
        ]

        subtitle = self._table_subtitle(table, mode)
        row_y = HEADER_HEIGHT + 8
        if subtitle and subtitle != self._table_title(table, mode):
            cells.append(
                "      "
                f'<mxCell id="{table_id}-subtitle" value="{self._xml(subtitle)}" '
                'style="text;html=1;strokeColor=none;fillColor=none;align=left;verticalAlign=middle;'
                'fontColor=#64748b;fontSize=9;spacingLeft=12;" '
                f'vertex="1" parent="{table_id}" connectable="0">'
                f'<mxGeometry x="0" y="{HEADER_HEIGHT + 2}" width="{self._num(rect.width())}" height="20" as="geometry"/>'
                "</mxCell>"
            )
            row_y = HEADER_HEIGHT + 25

        for column_index, column in enumerate(table.columns):
            font_style = "fontStyle=1;" if column.is_primary_key else ""
            cells.append(
                "      "
                f'<mxCell id="{table_id}-column-{column_index}" value="{self._xml(self._column_text(column, mode))}" '
                'style="text;html=1;strokeColor=none;fillColor=none;align=left;verticalAlign=middle;'
                f'fontColor=#0f172a;fontSize=10;spacingLeft=12;{font_style}" '
                f'vertex="1" parent="{table_id}" connectable="0">'
                f'<mxGeometry x="0" y="{self._num(row_y)}" width="{self._num(rect.width())}" height="{ROW_HEIGHT}" as="geometry"/>'
                "</mxCell>"
            )
            row_y += ROW_HEIGHT

        return cells

    def _drawio_bounds(self, boxes: dict[str, BoxGeometry]) -> QRectF:
        if not boxes:
            return QRectF(0, 0, BOX_WIDTH, HEADER_HEIGHT + ROW_HEIGHT + 16)
        rect = QRectF()
        for geometry in boxes.values():
            rect = rect.united(geometry.rect)
        return rect.adjusted(0, 0, 80, 80)

    def _table_title(self, table: TableModel, mode: str) -> str:
        return table.name if mode == "physical" else table.logical_name or table.name

    def _table_subtitle(self, table: TableModel, mode: str) -> str:
        return table.qualified_name if mode == "logical" else table.logical_name or ""

    def _column_text(self, column: ColumnModel, mode: str) -> str:
        flags = []
        if column.is_primary_key:
            flags.append("PK")
        if column.foreign_key:
            flags.append("FK")
        flag_text = f"[{','.join(flags)}] " if flags else ""
        if mode == "physical":
            null_text = "NULL" if column.nullable else "NOT NULL"
            return f"{flag_text}{column.name} : {column.data_type} {null_text}"
        return f"{flag_text}{column.logical_name}"

    def _drawio_header_color(self, mode: str) -> str:
        return "#1f2937" if mode == "physical" else "#155e75"

    def _xml(self, value: str) -> str:
        return escape(value or "", quote=True)

    def _num(self, value: float) -> str:
        if float(value).is_integer():
            return str(int(value))
        return f"{value:.2f}"
